spring.application.name=PS45101_NguyenHoangThienHau_ASM
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MotunPoLy;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# Thư mục lưu ảnh upload (nằm ngoài thư mục build/source, không cần restart server)
app.upload.dir=uploads/imges

# ===== Cấu hình SePay =====
sepay.api-key=sepay_MotunPoly_Thienhau041006

sepay.bank.account=0565032680
sepay.bank.name=MBBank
sepay.bank.holder=NGUYEN HOANG THIEN HAU

